component_depth: 1
languages:
- name: csharp
  production:
      exclude:      
      - /Taviloglu.Wrike.ApiClient.Tests.Integration/.*
      - /Taviloglu.Wrike.Core.Tests.Unit/.*
      - /Taviloglu.Wrike.ApiClient.Tests.Unit/.*      
      - /Taviloglu.Wrike.ApiClient.Samples/.*
      - /Taviloglu.Wrike.WebHook.Samples/.*
  test:
    include: 
      - /Taviloglu.Wrike.ApiClient.Tests.Integration/.*\.cs
      - /Taviloglu.Wrike.Core.Tests.Unit/.*\.cs
      - /Taviloglu.Wrike.ApiClient.Tests.Unit/.*\.cs
