component_depth: 1
languages:
- name: csharp
  production:
      exclude:      
      - /Taviloglu.Wrike.ApiClient.Tests.Integration/.*
      - /Taviloglu.Wrike.Core.Tests.Unit/.*
      - /Taviloglu.Wrike.ApiClient.Tests.Unit/.*      
      - /Taviloglu.Wrike.ApiClient.Samples/.*
      - /Taviloglu.Wrike.WebHook.Samples/.*
  test:
    exclude: 
      - /Taviloglu.Wrike.ApiClient.Extensions/.*
      - /Taviloglu.Wrike.ApiClient/.*
      - /Taviloglu.Wrike.Core/.*
      - /Taviloglu.Wrike.WebHook/.*
      - /Taviloglu.Wrike.ApiClient.Samples/.*
      - /Taviloglu.Wrike.WebHook.Samples/.*
